exclude: [".gitignore", ".ruby-version", "README.md", "Gemfile", "Gemfile.lock"]

highlighter: rouge

production_url : https://athega.se

lsi: true

permalink: /blogg/:year/:month/:day/:title

data_dir: _includes

collections:
  employees:
    output: true

sass:
  sass_dir: _includes
  style: compressed

compress_html:
  clippings: all

defaults:
  -
    scope:
      path: "assets"
    values:
      layout:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "blogg"
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
