exclude: [".gitignore", ".ruby-version", "README.md", "Gemfile", "Gemfile.lock"]

highlighter: rouge

production_url : https://athega.se

permalink: /blogg/:year/:month/:day/:title

data_dir: _includes

collections:
  employees:
    output: true

sass:
  sass_dir: _includes
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "employees"
    values:
      layout: "page"
  -
    scope:
      path: "blogg"
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
